//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jpinsoft.Class2GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_WPFGenerator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_WPFGenerator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jpinsoft.Class2GUI.Properties.Resources.WPFGenerator", typeof(Resources_WPFGenerator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GeneratedWPF {
            get {
                object obj = ResourceManager.GetObject("GeneratedWPF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBox x:Name=&quot;Txb{0}&quot;
        ///                         Grid.Row=&quot;{1}&quot;
        ///                         Grid.Column=&quot;{2}&quot;
        ///                         TabIndex=&quot;{3}&quot;                  Height=&quot;25&quot;
        ///                         Text=&quot;{{Binding {0},
        ///                                        NotifyOnValidationError=true,
        ///                                        UpdateSourceTrigger=PropertyChanged,
        ///                                        ValidatesOnDataErrors=true}}&quot; /&gt;.
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Border x:Name=&quot;Border{0}&quot; BorderThickness=&quot;0,0,0,1&quot; Grid.Row=&quot;{1}&quot; Grid.ColumnSpan=&quot;2&quot; Margin=&quot;0,0,0,0&quot;&gt;
        ///	                &lt;Border.BorderBrush&gt;
        ///        	            &lt;LinearGradientBrush EndPoint=&quot;0,0&quot; StartPoint=&quot;1,0&quot;&gt;
        ///                        	&lt;GradientStop Color=&quot;#FF3975A0&quot; Offset=&quot;0&quot;/&gt;
        ///                        &lt;GradientStop Color=&quot;#FFD3E2EC&quot; Offset=&quot;1&quot;/&gt;
        ///                	    &lt;/LinearGradientBrush&gt;
        ///        	        &lt;/Border.BorderBrush&gt;
        ///	            &lt;/Border&gt;
        ///
        ///		&lt;Label x:Name=&quot;Lbl{0}&quot;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Window x:Class=&quot;{0}.{2}Window&quot;
        ///        xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:sys=&quot;clr-namespace:System;assembly=mscorlib&quot;
        ///	{6}
        ///        Title=&quot;{2} Detail&quot;
        ///        WindowStartupLocation=&quot;CenterScreen&quot;
        ///        FontSize=&quot;14&quot;
        ///        Width=&quot;1000&quot;
        ///        Height=&quot;800&quot;&gt;
        ///    &lt;Window.Resources&gt;
        ///        &lt;ns01:DisplayNameConverter x:Key=&quot;displayNameConverter&quot; /&gt;
        ///	{5}
        ///    &lt;/Window.Resources&gt;
        ///
        ///    &lt;Wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private string {0};
        ///
        ///		[DisplayName(&quot;{1}:&quot;)]
        ///		public string {1}
        ///		{{
        ///			get {{ return {0}; }}
        ///			set {{ this.SetProperty(ref {0}, value); }}
        ///		}}.
        /// </summary>
        internal static string T004 {
            get {
                return ResourceManager.GetString("T004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CheckBox x:Name=&quot;Chb{0}&quot;
        ///                          Grid.Row=&quot;{1}&quot;
        ///                          Grid.Column=&quot;{2}&quot;
        ///                          TabIndex=&quot;{3}&quot;                  
        ///                          Margin=&quot;5,0&quot;
        ///                          VerticalAlignment=&quot;Center&quot;
        ///                          IsChecked=&quot;{{Binding {4}}}&quot; /&gt;.
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private bool {0};
        ///
        ///		[DisplayName(&quot;{1}:&quot;)]
        ///		public bool {1}
        ///		{{
        ///			get {{ return {0}; }}
        ///			set {{ this.SetProperty(ref {0}, value); }}
        ///		}}.
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ComboBox x:Name=&quot;cb{0}&quot;
        ///                  Grid.Row=&quot;{1}&quot;
        ///                  Grid.Column=&quot;{2}&quot;
        ///                  Height=&quot;25&quot;
        ///                  TabIndex=&quot;{3}&quot;
        ///                  SelectedItem=&quot;{{Binding {0}}}&quot; 
        ///                  ItemsSource=&quot;{{Binding {4}Source}}&quot; /&gt;.
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private {2}ViewModel {0};
        ///
        ///		[DisplayName(&quot;{1}:&quot;)]
        ///		public {2}ViewModel {1}
        ///		{{
        ///			get {{ return {0}; }}
        ///			set {{ this.SetProperty(ref {0}, value); }}
        ///		}}.
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public ObservableCollection&lt;{0}ViewModel&gt; {0}Source {{ get; set; }}.
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DockPanel Grid.Row=&quot;{1}&quot; Grid.Column=&quot;{2}&quot; Margin=&quot;5&quot;&gt;
        ///
        ///            &lt;StackPanel DockPanel.Dock=&quot;Right&quot;&gt;
        ///                &lt;Button x:Name=&quot;BtnAdd{4}&quot;
        ///                        Margin=&quot;3,0,3,3&quot;
        ///                        HorizontalContentAlignment=&quot;Left&quot;
        ///                        Click=&quot;BtnAdd{4}_Click&quot;
        ///                        Content=&quot;+ Pridať&quot;
        ///                        Padding=&quot;5&quot; /&gt;
        ///
        ///                &lt;Button x:Name=&quot;BtnUpdate{4}&quot;
        ///                        Margin=&quot;3,3&quot;
        ///                        HorizontalConte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DisplayName(&quot;{1}&quot;)]
        ///        public ObservableCollection&lt;{0}ViewModel&gt; {1} {{ get; set; }}
        ///
        ///        public {0}ViewModel {1}Selected
        ///        {{
        ///            get;
        ///            set;
        ///        }}
        ///
        ///        public void Add{1}({0}ViewModel item)
        ///        {{
        ///            {1}.Add(item);
        ///        }}
        ///
        ///        public void Remove{1}Selected()
        ///        {{
        ///            if ({1}Selected != null)
        ///                {1}.Remove({1}Selected);
        ///        }}.
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private void BtnAdd{0}_Click(object sender, RoutedEventArgs e)
        ///        {{
        ///            {1}Window addItemDialog = new {1}Window();
        ///
        ///            if (addItemDialog.ShowDialog() == true)
        ///                ViewModel.Add{0}(addItemDialog.ViewModel); 
        ///        }}
        ///
        ///        private void BtnUpdate{0}_Click(object sender, RoutedEventArgs e)
        ///        {{
        ///            new {1}Window(ViewModel.{0}Selected).ShowDialog();
        ///        }}
        ///
        ///        private void BtnRemove{0}_Click(object sender, RoutedEventArgs e)
        ///        {{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T012 {
            get {
                return ResourceManager.GetString("T012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///
        ///namespace {0}
        ///{{
        ///    /// &lt;summary&gt;
        ///    /// CODE WAS GENERATED BY WPF GENERATOR
        ///    /// Interaction logic for SampleXAML.xaml
        ///    /// &lt;/summary&gt;
        ///    public partial class {2} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T013 {
            get {
                return ResourceManager.GetString("T013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.ComponentModel;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///{1}
        ///
        ///namespace {0}
        ///{{
        ///    public class {2}ViewModel : ViewModelBase
        ///    {{
        ///        public {2}ViewModel()
        ///        {{
        ///        }}
        ///	{3}
        ///    }}
        ///}}.
        /// </summary>
        internal static string T014 {
            get {
                return ResourceManager.GetString("T014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Linq;
        ///using System.Runtime.CompilerServices;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace {0}
        ///{{
        ///    public class ViewModelBase : INotifyPropertyChanged
        ///    {{
        ///        #region Properties
        ///
        ///        public event PropertyChangedEventHandler PropertyChanged;
        ///
        ///        #endregion
        ///
        ///        #region Property changed
        ///
        ///        protected virtual bool SetProperty&lt;T&gt;(ref T storage, T value, 
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T015 {
            get {
                return ResourceManager.GetString("T015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Globalization;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Data;
        ///
        ///namespace {0}
        ///{{
        ///    public class DisplayNameConverter : IValueConverter
        ///    {{
        ///        #region Interface Implementations
        ///
        ///        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        ///        {{
        ///            return GetDisplayName(value, targetType, paramet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T016 {
            get {
                return ResourceManager.GetString("T016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DatePicker x:Name=&quot;DatePicker{0}&quot;
        ///                    Grid.Row=&quot;{1}&quot;
        ///                    Grid.Column=&quot;{2}&quot;
        ///                    Height=&quot;25&quot;
        ///                    VerticalAlignment=&quot;Center&quot;
        ///                    SelectedDate=&quot;{{Binding {0}}}&quot;
        ///                    TabIndex=&quot;{3}&quot; /&gt;.
        /// </summary>
        internal static string T017 {
            get {
                return ResourceManager.GetString("T017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private DateTime {0};
        ///
        ///		[DisplayName(&quot;{1}:&quot;)]
        ///		public DateTime {1}
        ///		{{
        ///			get {{ return {0}; }}
        ///			set {{ this.SetProperty(ref {0}, value); }}
        ///		}}.
        /// </summary>
        internal static string T018 {
            get {
                return ResourceManager.GetString("T018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DockPanel Grid.Row=&quot;{1}&quot;
        ///                   Grid.Column=&quot;{2}&quot;
        ///                   HorizontalAlignment=&quot;Stretch&quot;&gt;
        ///            &lt;TextBox x:Name=&quot;Txb{0}&quot;
        ///                     Width=&quot;60&quot;
        ///                     Height=&quot;25&quot;
        ///                     Margin=&quot;5,0&quot;
        ///                     DockPanel.Dock=&quot;Right&quot;
        ///                     Text=&quot;{{Binding ElementName=Slider{0},
        ///                                    Path=Value}}&quot; /&gt;
        ///            &lt;Slider x:Name=&quot;Slider{0}&quot;
        ///                    Height=&quot;25&quot;
        ///                    IsS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T019 {
            get {
                return ResourceManager.GetString("T019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private {2} {0};
        ///
        ///		[DisplayName(&quot;{1}:&quot;)]
        ///		public {2} {1}
        ///		{{
        ///			get {{ return {0}; }}
        ///			set {{ this.SetProperty(ref {0}, value); }}
        ///		}}.
        /// </summary>
        internal static string T020 {
            get {
                return ResourceManager.GetString("T020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Button x:Name=&quot;BtnOk&quot; 
        ///                Grid.Row=&quot;{0}&quot; 
        ///                Grid.Column=&quot;{1}&quot; 
        ///                Content=&quot;Ok&quot; 
        ///                Margin=&quot;0,30,200,10&quot;
        ///                HorizontalAlignment=&quot;Right&quot;
        ///                IsDefault=&quot;True&quot;                           
        ///                Width=&quot;150&quot; 
        ///                Height=&quot;36&quot; 
        ///                Click=&quot;BtnOk_Click&quot; /&gt;
        ///
        ///        &lt;Button x:Name=&quot;BtnCancel&quot; 
        ///                Content=&quot;Cancel&quot;   
        ///                Grid.Row=&quot;{0}&quot; 
        ///                Grid.Column=&quot;{1}&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T021 {
            get {
                return ResourceManager.GetString("T021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private void BtnOk_Click(object sender, RoutedEventArgs e)
        ///        {
        ///            this.DialogResult = true;
        ///            this.Close();
        ///        }.
        /// </summary>
        internal static string T022 {
            get {
                return ResourceManager.GetString("T022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ObjectDataProvider x:Key=&quot;{0}Source&quot; MethodName=&quot;GetValues&quot;
        ///                        ObjectType=&quot;{{x:Type sys:Enum}}&quot;&gt;
        ///            &lt;ObjectDataProvider.MethodParameters&gt;
        ///                &lt;x:Type TypeName=&quot;{1}:{0}&quot;/&gt;
        ///            &lt;/ObjectDataProvider.MethodParameters&gt;
        ///        &lt;/ObjectDataProvider&gt;.
        /// </summary>
        internal static string T023 {
            get {
                return ResourceManager.GetString("T023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ComboBox x:Name=&quot;cb{0}&quot;
        ///                  Grid.Row=&quot;{1}&quot;
        ///                  Grid.Column=&quot;{2}&quot;
        ///                  Height=&quot;25&quot;
        ///                  TabIndex=&quot;{3}&quot;
        ///                  SelectedItem=&quot;{{Binding {0}}}&quot; 
        ///                  ItemsSource=&quot;{{Binding Mode=OneWay, Source={{StaticResource {4}Source}} }}&quot; /&gt;.
        /// </summary>
        internal static string T024 {
            get {
                return ResourceManager.GetString("T024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private {2} {0};
        ///
        ///		[DisplayName(&quot;{1}:&quot;)]
        ///		public {2} {1}
        ///		{{
        ///			get {{ return {0}; }}
        ///			set {{ this.SetProperty(ref {0}, value); }}
        ///		}}.
        /// </summary>
        internal static string T025 {
            get {
                return ResourceManager.GetString("T025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:{0}=&quot;clr-namespace:{1};assembly={2}&quot;.
        /// </summary>
        internal static string T026 {
            get {
                return ResourceManager.GetString("T026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using {0};.
        /// </summary>
        internal static string T027 {
            get {
                return ResourceManager.GetString("T027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DockPanel Grid.Row=&quot;{1}&quot;
        ///                    Grid.Column=&quot;{2}&quot;&gt;
        ///            &lt;Button x:Name=&quot;btn{0}&quot;
        ///		    DockPanel.Dock=&quot;Right&quot; 
        ///                    Height=&quot;25&quot; 
        ///                    Margin=&quot;5&quot; 
        ///                    Padding=&quot;5&quot;
        ///		    Click=&quot;btn{0}_Click&quot;&gt;
        ///                ...
        ///            &lt;/Button&gt;
        ///            &lt;TextBox x:Name=&quot;txb{0}&quot;
        ///                  Height=&quot;25&quot;
        ///                  TabIndex=&quot;{3}&quot;
        ///                  IsReadOnly=&quot;True&quot;
        ///                  Text=&quot;{{Binding {0}}}&quot; /&gt;
        ///        &lt;/DockPanel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T028 {
            get {
                return ResourceManager.GetString("T028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private void btn{0}_Click(object sender, RoutedEventArgs e)
        ///        {{
        ///            {1}Window detailWindow = new {1}Window(this.ViewModel.{0});
        ///
        ///            detailWindow.ShowDialog();
        ///        }}.
        /// </summary>
        internal static string T029 {
            get {
                return ResourceManager.GetString("T029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Page Include=&quot;{0}&quot;&gt;
        ///      &lt;Generator&gt;MSBuild:Compile&lt;/Generator&gt;
        ///      &lt;SubType&gt;Designer&lt;/SubType&gt;
        ///    &lt;/Page&gt;.
        /// </summary>
        internal static string T030 {
            get {
                return ResourceManager.GetString("T030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Compile Include=&quot;{0}&quot;&gt;
        ///      &lt;DependentUpon&gt;{1}&lt;/DependentUpon&gt;
        ///    &lt;/Compile&gt;.
        /// </summary>
        internal static string T031 {
            get {
                return ResourceManager.GetString("T031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Compile Include=&quot;{0}&quot; /&gt;.
        /// </summary>
        internal static string T032 {
            get {
                return ResourceManager.GetString("T032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBox x:Name=&quot;Txb{0}&quot;
        ///                         Grid.Row=&quot;{1}&quot;
        ///                         Grid.Column=&quot;{2}&quot;
        ///                         TabIndex=&quot;{3}&quot;           
        ///                         Width=&quot;200&quot;
        ///                         Height=&quot;25&quot;
        ///                         HorizontalAlignment=&quot;Left&quot;
        ///                         Text=&quot;{{Binding {0}}}&quot; /&gt;.
        /// </summary>
        internal static string T033 {
            get {
                return ResourceManager.GetString("T033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private void BtnShow{0}_Click(object sender, RoutedEventArgs e)
        ///        {{
        ///            new {0}Window().ShowDialog();
        ///        }}.
        /// </summary>
        internal static string T034 {
            get {
                return ResourceManager.GetString("T034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Button
        ///            x:Name=&quot;BtnShow{0}&quot;
        ///            Width=&quot;185&quot;
        ///            Height=&quot;30&quot;
        ///            Margin=&quot;10&quot;
        ///            Click=&quot;BtnShow{0}_Click&quot;
        ///            Content=&quot;Show {0}&quot; /&gt;.
        /// </summary>
        internal static string T035 {
            get {
                return ResourceManager.GetString("T035", resourceCulture);
            }
        }
    }
}
